version: 2

updates:
- package-ecosystem: npm
  directory: /
  versioning-strategy: increase-if-necessary
  schedule:
    interval: weekly
  groups:
    production-dependencies:
      dependency-type: "production"
    development-dependencies:
      dependency-type: "development"
  ignore:
    - dependency-name: "chai"
        # chai 5 doesn't work atm w/ cds.test, TODO fix that in cds.test
      versions: ["5.x"]
    - dependency-name: "chai-as-promised"
        # chai-as-promised 7 doesn't work atm w/ cds.test, TODO fix that in cds.test
      versions: ["7.x"]
